title: Fasta Robotics Documentation
description: Documentation for using robots of Fasta Robotics Company
theme: just-the-docs

url: https://FastaRobotics.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

logo: "fastalogo.png"

